include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_Gad

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework -I../../core

t_Gad_OBJC_FILES = t_Gad.m
t_Gad_TOOL_LIBS += -ldispatch

include $(GNUSTEP_MAKEFILES)/test-tool.make
