#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
# Writes src/qt-metadata.h: the plugin metadata Qt wants, without Qt.
#   Qt 5 scans the plugin file for "QTMETADATA !" followed by the data.
#   Qt 6 reads an ELF note named "qt-project!" from the section .qtmetadata.
# Both carry the same CBOR map: interface id, class name and the theme key.
import sys

KEY = b"gad"
IID = b"org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1"
CLASS = b"QGadThemePlugin"

def text(b):
    assert len(b) < 24
    return bytes([0x60 + len(b)]) + b

cbor = (b"\xbf" + b"\x02" + b"\x78" + bytes([len(IID)]) + IID
        + b"\x03" + text(CLASS)
        + b"\x04" + b"\xa1" + text(b"Keys") + b"\x81" + text(KEY) + b"\xff")

# Qt 5: format 0, Qt 5.15, release
qt5 = b"QTMETADATA !" + bytes([0, 5, 15, 0]) + cbor
# Qt 6: format 1, Qt 6.8, flag 1 as in the distribution's plugins; padded to a multiple of 4 as ELF notes are
desc = bytes([1, 6, 8, 1]) + cbor
desc += b"\0" * (-len(desc) % 4)
note = ((12).to_bytes(4, "little") + len(desc).to_bytes(4, "little")
        + (0x74510001).to_bytes(4, "little") + b"qt-project!\0" + desc)

def array(name, data):
    body = ",".join(str(x) for x in data)
    return "__attribute__((used)) static const unsigned char %s[%d] = {%s};\n" % (name, len(data), body)

out = "/* Generated by tools/gen-qt-metadata.py - do not edit. */\n"
# Qt 5 on ELF reads the sections .qtversion (what Qt it was built for) and
# .qtmetadata; the first word is a size/arch check value copied from a real plugin
qtversion = bytes([0x58]) + b"\xff" * 7 + bytes([0, 15, 5, 0]) + b"\0" * 4
out += ('__attribute__((used, section(".qtversion"), aligned(8))) const unsigned char gad_qt5_version[16] = {%s};\n'
        % ",".join(str(x) for x in qtversion))
out += ('__attribute__((used, section(".qtmetadata"), aligned(32))) const unsigned char gad_qt5_metadata[%d] = {%s};\n'
        % (len(qt5), ",".join(str(x) for x in qt5)))
out += array("gad_qt6_desc", desc)
# the note itself has to be a real SHT_NOTE section, which C attributes cannot make
out += '__asm__(".pushsection .note.qt.metadata,\\"a\\",@note\\n.balign 8\\n.long 12\\n.long %d\\n.long 0x74510001\\n.asciz \\"qt-project!\\"\\n%s.popsection\\n");\n' % (
    len(desc), "".join('.byte %d\\n' % b for b in desc))
open(sys.argv[1] if len(sys.argv) > 1 else "src/qt-metadata.h", "w").write(out)
