include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

APP_NAME = Todo

Todo_OBJC_FILES = \
	main.m \
	TDTask.m \
	TDList.m \
	TDMarkdownCodec.m \
	TDLineMerge.m \
	TDURLConnectionTransport.m \
	TDGistClient.m \
	TDPreferences.m \
	TDStore.m \
	TDTexture.m \
	TDTaskTitleCell.m \
	TDSidebarTableView.m \
	TDTaskOutlineView.m \
	TDMainWindowController.m \
	TDPreferencesWindowController.m \
	TDAppDelegate.m

ADDITIONAL_OBJCFLAGS += -Wall -Wno-deprecated

include $(GNUSTEP_MAKEFILES)/application.make
