include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

APP_NAME = Docket

Docket_OBJC_FILES = \
	main.m \
	DKTask.m \
	DKList.m \
	DKMarkdownCodec.m \
	DKLineMerge.m \
	DKURLConnectionTransport.m \
	DKGistClient.m \
	DKPreferences.m \
	DKStore.m \
	DKTexture.m \
	DKTaskTitleCell.m \
	DKSidebarTableView.m \
	DKTaskOutlineView.m \
	DKMainWindowController.m \
	DKPreferencesWindowController.m \
	DKAppDelegate.m

ADDITIONAL_OBJCFLAGS += -Wall -Wno-deprecated

include $(GNUSTEP_MAKEFILES)/application.make
